import 'package:flutter_test/flutter_test.dart';
import 'package:aura_one/services/ai/ai_journal_generator.dart';
import 'package:aura_one/services/ai/journal_generation_policy.dart';
import 'package:aura_one/services/daily_context_synthesizer.dart';

void main() {
  test('returns generated content for a successful adapter result', () {
    final content = resolveGeneratedNarrative(
      adapter: _FakeAdapter(),
      result: AIGenerationResult.success('Generated by Gemma'),
    );

    expect(content, 'Generated by Gemma');
  });

  test('throws when no adapter is available', () {
    expect(
      () => resolveGeneratedNarrative(adapter: null, result: null),
      throwsA(isA<JournalGenerationUnavailableException>()),
    );
  });

  test('throws with the adapter error when generation fails', () {
    expect(
      () => resolveGeneratedNarrative(
        adapter: _FakeAdapter(),
        result: AIGenerationResult.failure('Gemma is not installed'),
      ),
      throwsA(
        isA<JournalGenerationUnavailableException>().having(
          (e) => e.message,
          'message',
          'Gemma is not installed',
        ),
      ),
    );
  });
}

class _FakeAdapter implements AIJournalGenerator {
  @override
  Future<bool> checkAvailability() async => true;

  @override
  Future<AIGenerationResult> describeImage(String imagePath) async =>
      AIGenerationResult.failure('unused');

  @override
  Future<bool> downloadRequiredAssets({
    void Function(double p1)? onProgress,
  }) async => true;

  @override
  Future<AIGenerationResult> generateSummary(DailyContext context) async =>
      AIGenerationResult.failure('unused');

  @override
  AICapabilities getCapabilities() {
    return AICapabilities(
      canGenerateSummary: true,
      canDescribeImage: false,
      canRewriteText: false,
      isOnDevice: true,
      requiresNetwork: false,
      supportedLanguages: {'en'},
      supportedTones: {'friendly'},
      adapterName: 'GemmaLocal',
      tierLevel: 3,
    );
  }

  @override
  Future<AIGenerationResult> rewriteText(
    String text, {
    String? tone,
    String? language,
  }) async => AIGenerationResult.failure('unused');
}
